- type: job
  id: EmpireMedico
  name: job-name-empire-medico
  description: job-description-empire-medico
  playTimeTracker: JobEmpireMedico
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200
  startingGear: MedicoGear
  icon: "JobIconMedicalDoctor"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: DoctorDay
    prototype: WehMedipen

- type: startingGear
  id: MedicoGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled